package org.b333vv.metric.cli;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Golden (snapshot) contract tests for the JSON emitted by the {@code analyze}, {@code validate} and
 * {@code detect} commands.
 *
 * <p>Every test runs the real pipeline in-process — {@link JavaMetricsCliApplication} with the
 * production {@link MetricReportJsonWriter}, {@link ValidateCommand} writer and
 * {@link DetectResultWriter} — over the synthetic fixture project in
 * {@code src/test/resources/golden-project}, and compares the result with the checked-in golden
 * files in {@code src/test/resources/golden}. The fixtures for thresholds and detection rules live
 * in {@code src/test/resources/golden-config}.
 *
 * <h2>What the fixture covers</h2>
 * <ul>
 *   <li>inheritance ({@code a.Derived extends a.Base}),</li>
 *   <li>interfaces ({@code a.Marker} with a default method),</li>
 *   <li>static calls ({@code Math.abs}),</li>
 *   <li>nested and inner classes ({@code a.Outer.Nested}, {@code a.Outer.Inner}),</li>
 *   <li>a deliberately unresolvable reference ({@code a.Unresolvable} →
 *       {@code missing.dependency.AbsentService}),</li>
 *   <li>two packages: {@code a} and {@code a.b}.</li>
 * </ul>
 *
 * <h2>Normalisation before comparison</h2>
 * <p>Absolute paths are the only volatile part of the output, so the test rewrites the absolute
 * path of the fixture project to the {@code <GOLDEN_PROJECT>} placeholder and normalises path
 * separators to {@code /}. Everything else is compared verbatim: JSON is only pretty-printed (key
 * order and values are preserved) to keep the golden files and the failure diffs readable.
 *
 * <p>Metric values are emitted as strings formatted by {@code Value.toString()}, which uses a
 * {@code DecimalFormat} created from the JVM default locale — on a Russian locale that yields
 * {@code "53,8887"} instead of {@code "53.8887"}. The {@code test} task therefore pins
 * {@code user.language=en} / {@code user.country=US} for the whole test JVM; see DEBT-07 in
 * {@code docs/tech-debt-tracker.md} for the underlying contract defect.
 *
 * <h2>Regenerating the golden files</h2>
 * <p>Golden files must only be regenerated by an explicit developer action, and the resulting diff
 * must be reviewed like any other code change — an updated golden that nobody looks at turns this
 * suite into a rubber stamp.
 *
 * <pre>{@code
 * ./gradlew :java-metrics-cli:test --tests '*JsonContractGoldenTest' -Dgoldens.update=true
 * }</pre>
 *
 * <p>This rewrites {@code java-metrics-cli/src/test/resources/golden/*.json} and passes. The
 * property is forwarded to the test JVM by the {@code test} task in
 * {@code java-metrics-cli/build.gradle.kts}; {@code -Pgoldens.update=true} is accepted as well.
 * See {@code docs/RUN.md} for the documented procedure.
 */
class JsonContractGoldenTest {

    /**
     * Explicit, documented switch that rewrites the golden files instead of comparing against them.
     */
    private static final String UPDATE_GOLDENS_PROPERTY = "goldens.update";

    /** Placeholder replacing the absolute path of the fixture project (and everything below it). */
    private static final String PROJECT_PLACEHOLDER = "<GOLDEN_PROJECT>";

    private static final String GOLDEN_PROJECT_NAME = "golden-project";

    private static final String FIXTURE_RELATIVE_PATH = "src/test/resources/golden-project";

    /** Upper bound on the differing lines reported when a golden comparison fails. */
    private static final int MAX_REPORTED_DIFFERENCES = 10;

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private static final boolean UPDATE_GOLDENS =
            Boolean.parseBoolean(System.getProperty(UPDATE_GOLDENS_PROPERTY, "false"));

    @Test
    void analyzeCommandJsonMatchesGolden() throws Exception {
        ExecutionResult result = runCli(
                "analyze",
                "--source-root", fixtureProjectRoot().resolve("src").toString(),
                "--project-name", GOLDEN_PROJECT_NAME);

        assertEquals(0, result.exitCode(), result.stderr());
        assertFixtureIsAnalysed(result.stdout());
        assertGolden("analyze.json", result.stdout());
    }

    @Test
    void validateCommandJsonMatchesGolden(@TempDir Path tempDir) throws Exception {
        Path reportFile = tempDir.resolve("validate-report.json");

        ExecutionResult result = runCli(
                "validate",
                "--source", fixtureProjectRoot().resolve("src").toString(),
                "--thresholds", goldenConfigFile("thresholds.json").toString(),
                "--output", reportFile.toString());

        assertEquals(0, result.exitCode(), result.stderr());
        assertGolden("validate.json", Files.readString(reportFile));
    }

    @Test
    void detectCommandJsonMatchesGolden(@TempDir Path tempDir) throws Exception {
        Path reportFile = tempDir.resolve("detect-report.json");

        ExecutionResult result = runCli(
                "detect",
                "--source", fixtureProjectRoot().resolve("src").toString(),
                "--class-rules", goldenConfigFile("class-rules.json").toString(),
                "--package-rules", goldenConfigFile("package-rules.json").toString(),
                "--output", reportFile.toString());

        assertEquals(0, result.exitCode(), result.stderr());
        assertGolden("detect.json", Files.readString(reportFile));
    }

    /**
     * Guards the fixture itself: if the golden project stops producing the expected classes, the
     * contract tests would silently degrade into "compare empty output with empty golden".
     */
    private static void assertFixtureIsAnalysed(String analyzeJson) throws JsonProcessingException {
        JsonNode root = OBJECT_MAPPER.readTree(analyzeJson);
        List<String> qualifiedNames = new ArrayList<>();
        root.path("project").path("packages").forEach(packageNode -> {
            assertTrue(
                    !packageNode.path("packageName").asText().isEmpty(),
                    "Golden project must report at least one package with a non-empty name");
            packageNode.path("classes").forEach(classNode ->
                    qualifiedNames.add(classNode.path("qualifiedName").asText()));
        });

        assertTrue(
                qualifiedNames.containsAll(List.of(
                        "a.Base",
                        "a.Derived",
                        "a.Marker",
                        "a.Outer",
                        "a.Outer.Inner",
                        "a.Outer.Nested",
                        "a.Unresolvable",
                        "a.b.Helper")),
                "Golden project fixture is incomplete, analysed classes were: " + qualifiedNames);
    }

    private ExecutionResult runCli(String... args) throws IOException {
        ByteArrayOutputStream stdout = new ByteArrayOutputStream();
        ByteArrayOutputStream stderr = new ByteArrayOutputStream();
        int exitCode = new JavaMetricsCliApplication().run(
                args,
                new PrintWriter(stdout, true, StandardCharsets.UTF_8),
                new PrintWriter(stderr, true, StandardCharsets.UTF_8));
        return new ExecutionResult(
                exitCode,
                stdout.toString(StandardCharsets.UTF_8),
                stderr.toString(StandardCharsets.UTF_8));
    }

    private void assertGolden(String goldenFileName, String rawJson) throws IOException {
        String actual = canonicalize(prettyPrint(rawJson));
        Path goldenFile = goldenDir().resolve(goldenFileName);

        if (UPDATE_GOLDENS) {
            Files.createDirectories(goldenFile.getParent());
            Files.writeString(goldenFile, actual);
            System.out.println("[goldens] updated " + goldenFile);
            return;
        }

        if (!Files.exists(goldenFile)) {
            fail("Missing golden file " + goldenFile
                    + ". Generate it with -D" + UPDATE_GOLDENS_PROPERTY + "=true and review the diff.");
        }

        String expected = readNormalized(goldenFile);
        if (!expected.equals(actual)) {
            fail("JSON contract of '" + goldenFileName + "' changed.\n"
                    + "If the change is intentional, regenerate the golden files with "
                    + "-D" + UPDATE_GOLDENS_PROPERTY + "=true and review the diff.\n"
                    + diff(expected, actual));
        }
    }

    /**
     * Replaces the absolute path of the fixture project with {@link #PROJECT_PLACEHOLDER} and
     * normalises path separators so that golden files are independent of the checkout location and
     * of the operating system.
     */
    private static String canonicalize(String json) {
        String root = fixtureProjectRoot().toAbsolutePath().normalize().toString();
        String canonical = json
                .replace(jsonEscaped(root), PROJECT_PLACEHOLDER)
                .replace(root, PROJECT_PLACEHOLDER)
                .replace(root.replace('\\', '/'), PROJECT_PLACEHOLDER);
        return canonical.replace("\\\\", "/").replace('\\', '/');
    }

    private static String jsonEscaped(String value) {
        return value.replace("\\", "\\\\");
    }

    /**
     * Pretty-prints the emitted JSON without changing key order or values. Also fails fast with a
     * readable message when the command wrote something that is not valid JSON — for example a
     * stray {@code System.out.println} next to the report on stdout.
     */
    private static String prettyPrint(String rawJson) {
        try {
            JsonNode tree = OBJECT_MAPPER.readTree(rawJson);
            return OBJECT_MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(tree) + "\n";
        } catch (JsonProcessingException exception) {
            return fail("Command output is not valid JSON: " + rawJson, exception);
        }
    }

    private static String readNormalized(Path file) throws IOException {
        return Files.readString(file).replace("\r\n", "\n");
    }

    private static String diff(String expected, String actual) {
        List<String> expectedLines = List.of(expected.split("\n", -1));
        List<String> actualLines = List.of(actual.split("\n", -1));
        StringBuilder report = new StringBuilder("First differing lines (golden vs actual):\n");
        int reported = 0;
        int lineCount = Math.max(expectedLines.size(), actualLines.size());
        for (int index = 0; index < lineCount && reported < MAX_REPORTED_DIFFERENCES; index++) {
            String expectedLine = index < expectedLines.size() ? expectedLines.get(index) : "<missing line>";
            String actualLine = index < actualLines.size() ? actualLines.get(index) : "<missing line>";
            if (!expectedLine.equals(actualLine)) {
                reported++;
                report.append("  line ").append(index + 1).append(":\n")
                        .append("    golden: ").append(expectedLine).append('\n')
                        .append("    actual: ").append(actualLine).append('\n');
            }
        }
        if (reported == 0) {
            report.append("  (line content matches; the files differ only in length)\n");
        }
        return report.toString();
    }

    private static Path fixtureProjectRoot() {
        return cliProjectDir().resolve(FIXTURE_RELATIVE_PATH);
    }

    private static Path goldenDir() {
        return cliProjectDir().resolve("src/test/resources/golden");
    }

    private static Path goldenConfigFile(String fileName) {
        return cliProjectDir().resolve("src/test/resources/golden-config").resolve(fileName);
    }

    /**
     * Locates the {@code java-metrics-cli} module directory: the explicitly configured system
     * property wins, otherwise the working directory (Gradle sets it to the module directory) or one
     * of its parents is used, which also covers running the test from the repository root.
     */
    private static Path cliProjectDir() {
        String configured = System.getProperty("goldenCliProjectDir");
        if (configured != null && !configured.isBlank()) {
            return Path.of(configured).toAbsolutePath().normalize();
        }

        Path candidate = Path.of("").toAbsolutePath().normalize();
        while (candidate != null) {
            if (Files.isDirectory(candidate.resolve(FIXTURE_RELATIVE_PATH))) {
                return candidate;
            }
            Path nested = candidate.resolve("java-metrics-cli");
            if (Files.isDirectory(nested.resolve(FIXTURE_RELATIVE_PATH))) {
                return nested;
            }
            candidate = candidate.getParent();
        }

        throw new IllegalStateException("Unable to locate " + FIXTURE_RELATIVE_PATH
                + " from " + Path.of("").toAbsolutePath() + "; set -DgoldenCliProjectDir=<module dir>");
    }

    private record ExecutionResult(int exitCode, String stdout, String stderr) {
    }
}
