import java.security.MessageDigest

plugins {
    id("application")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

configurations {
    val testImplementation = configurations.getByName("testImplementation")
    val testRuntimeOnly = configurations.getByName("testRuntimeOnly")

    create("integrationTestImplementation") {
        extendsFrom(testImplementation)
    }
    create("integrationTestRuntimeOnly") {
        extendsFrom(testRuntimeOnly)
    }
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

sourceSets {
    val main by getting
    create("integrationTest") {
        compileClasspath += main.output
        runtimeClasspath += main.output
        java.srcDir("src/integration-test/java")
        resources.srcDir("src/integration-test/resources")
    }
}

dependencies {
    implementation(project(":java-metrics-lib"))
    implementation("info.picocli:picocli:4.7.6")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.2")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0")
}

application {
    mainClass.set("org.b333vv.metric.cli.JavaMetricsCliMain")
}

/**
 * Writes the build version into a resource the tool reads at runtime.
 *
 * <p>Generated rather than maintained by hand because a hand-maintained version is wrong exactly
 * when it matters: on the day someone bumps the build. One source, read by `--version`, by the JSON
 * report and by SARIF, so a user can never be told two different things about which build ran.
 */
val metricsVersion: String = (rootProject.extra["metricsVersion"] as String?) ?: "0.0.0-dev"

val generateVersionResource by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/resources/version")
    val version = metricsVersion
    inputs.property("metricsVersion", version)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile.resolve("metricstree-version.properties")
        file.parentFile.mkdirs()
        file.writeText(
            """
            # Generated by the build. Do not edit: the next build overwrites this file.
            metrics.version=${version}
            """.trimIndent() + System.lineSeparator()
        )
    }
}

sourceSets["main"].resources.srcDir(generateVersionResource)
tasks.named("processResources") { dependsOn(generateVersionResource) }

tasks.test {
    useJUnitPlatform()

    // Metric values are serialized as strings produced by Value.toString(), which formats doubles
    // with a DecimalFormat created from the default locale (see DEBT-07). Pinning the locale keeps
    // the JSON contract goldens reproducible on machines with a non-English locale.
    systemProperty("user.language", "en")
    systemProperty("user.country", "US")

    // The documentation tests read README, RUN and the shipped example configs from the source
    // tree, so the repository root is passed rather than assumed: a test run from an IDE with a
    // different working directory would otherwise check nothing and pass.
    // The repository root, not this module: the documents under test are README.md and docs/,
    // which sit above java-metrics-cli. Resolved from the module directory so it does not depend
    // on the working directory a test happens to run in.
    systemProperty("docsRepoRoot", layout.projectDirectory.dir("..").asFile.absolutePath)

    // Golden (snapshot) tests of the JSON output contract resolve their fixtures from the source
    // tree, so the module directory is passed explicitly instead of relying on the working
    // directory. See org.b333vv.metric.cli.JsonContractGoldenTest.
    systemProperty("goldenCliProjectDir", layout.projectDirectory.asFile.absolutePath)

    // Regeneration of the golden files is an explicit developer action:
    //   ./gradlew :java-metrics-cli:test -Dgoldens.update=true
    // Gradle does not forward command-line -D properties to test JVMs, so do it here.
    providers.gradleProperty("goldens.update")
            .orElse(providers.systemProperty("goldens.update"))
            .orNull
            ?.let { systemProperty("goldens.update", it) }
}

tasks.register<Test>("integrationTest") {
    description = "Runs Java Metrics CLI distribution smoke tests."
    group = "verification"
    testClassesDirs = sourceSets["integrationTest"].output.classesDirs
    classpath = sourceSets["integrationTest"].runtimeClasspath
    dependsOn(tasks.installDist)
    dependsOn(tasks.named("unpackDistribution"))
    // The shadow jar is the artifact users actually download, and it is built with minimize(), which
    // strips classes it cannot prove are reachable. The JSON contract is reached reflectively (record
    // accessors, mixins, custom serializers), so it can only be proven against the packaged jar.
    dependsOn(tasks.shadowJar)
    shouldRunAfter(tasks.test)
    useJUnitPlatform()
    systemProperty(
            "javaMetricsCliBinary",
            layout.buildDirectory.file("install/java-metrics-cli/bin/java-metrics-cli").get().asFile.absolutePath)
    systemProperty(
            "javaMetricsCliBatBinary",
            layout.buildDirectory.file("install/java-metrics-cli/bin/java-metrics-cli.bat").get().asFile.absolutePath)
    systemProperty(
            "javaMetricsCliShadowJar",
            tasks.shadowJar.get().archiveFile.get().asFile.absolutePath)
    // The version and the unpacked distribution, so the artifact tests assert against the build
    // rather than against a hard-coded number that would drift on the next bump.
    systemProperty("javaMetricsCliVersion", metricsVersion)
    // The action's script, so the consumer tests exercise the same file the action runs rather than
    // a copy of it. A test of a reimplementation proves nothing about the thing that ships.
    systemProperty(
            "metricsGateActionScript",
            rootProject.file("scripts/run-metrics-gate-action.sh").absolutePath)
    systemProperty(
            "javaMetricsCliDistribution",
            layout.buildDirectory.dir("dist-unpacked/java-metrics-cli").get().asFile.absolutePath)
}

// `check` is the gate AGENTS.md names, so the distribution proof has to be part of it. Without this
// the integration test only runs when someone remembers to ask for it, which is exactly how a
// minimize() regression reaches users: it passes every unit test and fails at the first analyze.
tasks.check {
    dependsOn(tasks.named("integrationTest"))
}

tasks.shadowJar {
    archiveBaseName.set("java-metrics")
    archiveClassifier.set("")
    minimize()
    mergeServiceFiles()
    // minimize() keeps only what it can prove is reachable. The rule catalogue and the version are
    // read as classpath resources at runtime, which no bytecode reference mentions, so the minimizer
    // cannot see them and would strip them. The artifact would then start and analyse nothing --
    // an integration test asserts they survive.
    filesMatching(listOf("maintainability/**", "metricstree-version.properties", "profiles/**")) {
                // Kept: no action, the pattern is what is wanted.
    }
}

/**
 * A versioned, ready-to-run distribution: the launcher, the jars, the licence, and checksums.
 *
 * <p>This is the artifact a consumer unzips and runs, and the point of ML-028. The alternative --
 * "clone the repository and run Gradle" -- asks a consumer to build an analyzer before they can
 * analyse anything, which is a build toolchain in the way of every question they wanted to ask.
 *
 * <p>Checksums are generated here rather than at release time, because a checksum computed by the
 * same build that produced the bytes is the only one that cannot disagree with them.
 */
// Named outside the task so the Kotlin script resolves `java.security` from the root package rather
// than from the build-script's own namespaces.
fun sha256Hex(bytes: ByteArray): String =
    MessageDigest.getInstance("SHA-256").digest(bytes)
        .joinToString("") { byte -> "%02x".format(byte) }

val distributionZip = tasks.register<Zip>("distributionZip") {
    group = "distribution"
    description = "Builds the ready-to-run distribution archive with licences and checksums."
    archiveBaseName.set("metricstree-cli")
    archiveVersion.set(metricsVersion)
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))

    val launcher = tasks.installDist
    val shadow = tasks.shadowJar
    val licence = rootProject.file("LICENSE")
    dependsOn(launcher, shadow, tasks.processResources)

    // The launcher and the shadow jar are both shipped: the first needs an unpacked layout, the
    // second is what a user without a launcher script (a container, a one-line CI step) runs.
    from(launcher.map { it.destinationDir }) {
        into("metricstree-cli")
    }
    from(shadow.map { it.archiveFile }) {
        into("metricstree-cli")
        rename { "metricstree-cli-all.jar" }
    }
    from(licence) {
        into("metricstree-cli")
    }
    from(rootProject.file("docs/RUN.md")) {
        into("metricstree-cli")
        rename { "README.md" }
    }

}

/**
 * The checksum manifest, produced as its own task.
 *
 * <p>Separate because a {@code Zip} cannot take new inputs once it starts executing, and a checksum
 * list is an input. It also keeps the intent readable: this task hashes files, that one packages
 * them.
 */
val distributionChecksums = tasks.register("distributionChecksums") {
    group = "distribution"
    description = "Writes SHA256SUMS for the unpacked distribution."
    val launcher = tasks.installDist
    val shadow = tasks.shadowJar
    val licence = rootProject.file("LICENSE")
    val outputFile = layout.buildDirectory.file("dist-checksums/SHA256SUMS")
    inputs.dir(launcher.map { it.destinationDir })
    inputs.file(shadow.map { it.archiveFile })
    inputs.file(licence)
    outputs.file(outputFile)
    doLast {
        val staging = layout.buildDirectory.dir("tmp/dist-checksums").get().asFile
        staging.deleteRecursively()
        staging.mkdirs()
        val project = project
        project.copy {
            from(launcher.get().destinationDir)
            into(staging)
        }
        project.copy {
            from(shadow.get().archiveFile)
            into(staging)
            rename { "metricstree-cli-all.jar" }
        }
        project.copy {
            from(licence)
            into(staging)
        }

        val lines = staging.walkTopDown().filter { it.isFile }.sortedBy { it.toString() }
            .map { file ->
                "${sha256Hex(file.readBytes())}  " +
                    file.relativeTo(staging).invariantSeparatorsPath
            }
        val target = outputFile.get().asFile
        target.parentFile.mkdirs()
        target.writeText(lines.joinToString("\n") + "\n")
    }
}

tasks.named<Zip>("distributionZip") {
    from(distributionChecksums.map { layout.buildDirectory.file("dist-checksums/SHA256SUMS") }) {
        into("metricstree-cli")
    }
}

/**
 * The checksum of the archive itself, for a release to publish beside it.
 *
 * <p>Separate from {@code SHA256SUMS} on purpose: one lists the contents of the unpacked tree, the
 * other identifies the single file a user downloads. Confusing the two is how a checksum ends up
 * verifying the wrong bytes.
 */
/**
 * The distribution unpacked where the artifact tests can run it.
 *
 * <p>Produced by the build rather than by the test, so the tests exercise the same bytes the archive
 * carries. A test that unzipped its own copy would be testing a second build of the same inputs.
 */
val unpackDistribution = tasks.register<Sync>("unpackDistribution") {
    group = "distribution"
    description = "Unpacks the ready-to-run distribution for the artifact tests."
    dependsOn(tasks.installDist, tasks.shadowJar, tasks.named("distributionChecksums"))
    from(tasks.installDist.map { it.destinationDir })
    from(tasks.shadowJar.map { it.archiveFile }) { rename { "metricstree-cli-all.jar" } }
    from(tasks.named("distributionChecksums")
            .map { layout.buildDirectory.file("dist-checksums/SHA256SUMS") })
    from(rootProject.file("LICENSE"))
    into(layout.buildDirectory.dir("dist-unpacked/java-metrics-cli"))
}

val archiveChecksum = tasks.register("archiveChecksum") {
    group = "distribution"
    description = "Writes the SHA-256 of the distribution archive."
    val archive = tasks.named<Zip>("distributionZip").flatMap { it.archiveFile }
    val output = layout.buildDirectory.file("dist-checksums/metricstree-cli.sha256")
    inputs.file(archive)
    outputs.file(output)
    doLast {
        val file = output.get().asFile
        file.parentFile.mkdirs()
        file.writeText(sha256Hex(archive.get().asFile.readBytes()) + "  "
                + archive.get().asFile.name + "\n")
    }
}

tasks.named<Zip>("distributionZip") {
    finalizedBy(archiveChecksum)
}

tasks.assemble {
    dependsOn(distributionZip)
}
